"""
https://platform.openai.com/docs/guides/function-calling
"""

import json
from pprint import pprint
from openai import OpenAI
from pydantic import Field
from pydantic_settings import BaseSettings


class Settings(BaseSettings):
    model: str = Field("gpt-4.1")
    base_url: str = Field(..., alias="openai_base_url")
    api_key: str = Field(..., alias="openai_api_key")


def try_dict_from_json(text: str) -> dict:
    try:
        return json.loads(text)
    except Exception:
        return {}


def main():
    settings = Settings()  # type: ignore
    model = settings.model
    client = OpenAI(
        base_url=settings.base_url,
        api_key=settings.api_key,
    )
    tools = [
        {
            "type": "function",
            "name": "calculate",
            "description": "Calculate the result of two numbers",
            "parameters": {
                "type": "object",
                "properties": {"a": {"type": "number"}, "b": {"type": "number"}},
                "required": ["a", "b"],
            },
        },
    ]
    messages = [
        {"role": "user", "content": "3 和 5 计算 等于多少"},
        {"role": "user", "content": "3.5 和 5.1 计算等于多少"},
    ]
    response = client.responses.create(model=model, tools=tools, input=messages)  # type: ignore
    pprint(response.model_dump())

    messages += response.output
    for item in response.output:
        if item.type == "function_call":
            if item.name == "calculate":
                arguments = try_dict_from_json(item.arguments)
                a, b = arguments.get("a"), arguments.get("b")
                if isinstance(a, (int, float)) and isinstance(b, (int, float)):
                    result = (a + b) * 10
                    messages.append(
                        {
                            "type": "function_call_output",
                            "call_id": item.call_id,
                            "output": json.dumps({"result": result}),
                        }
                    )
    if len(messages) <= 2:
        print("function not found.")
    else:
        response = client.responses.create(
            model=model,
            instructions="Respond only with result generated by a tool.",
            tools=tools,  # type: ignore
            input=messages,  # type: ignore
        )

        print("Final output:")
        print("\n" + response.output_text)


if __name__ == "__main__":
    main()
